[package]
name = "tcp-bridge"
version = "0.1.0"
authors = ["hellbox"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
quinn = "0.6.1"
webpki = "0.21.0"
rustls = { version = "0.17.0", features = ["dangerous_configuration"] }
tokio = { version = "0.2.20", features = ["rt-threaded", "time", "macros", "stream", "sync", "io-util", "tcp"] }
