name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_bridge:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./kissmp-bridge
      run: cargo build --verbose --release
    - name: Store Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build_results
        path: |
          ./kissmp-bridge/target/release/kissmp-bridge
          ./kissmp-bridge/target/release/kissmp-bridge.exe
  build_server:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./kissmp-server
      run: cargo build --verbose --release
    - name: Store Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build_results
        path: |
          ./kissmp-server/target/release/kissmp-server
          ./kissmp-server/target/release/kissmp-server.exe

  build_master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      working-directory: ./kissmp-master
      run: cargo build --verbose --release
    - name: Store Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build_results
        path: |
          ./kissmp-master/target/release/kissmp-master
